BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Unit] ADD [createdAt] DATETIME2 NOT NULL CONSTRAINT [Unit_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
[dateTimeIn] DATETIME2,
[dateTimeUpdate] DATETIME2,
[updatedAt] DATETIME2;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
